
class Error_Codes():
    UNEXPECTED_MESSAGE_TYPE = 1
    UNKNOWN_MESSAGE_TYPE = 2
    LENGTH_ERROR = 3
    BAD_SESSION_ID = 4
    UNSUPPORTED_FIELD = 5
    UNSUPPORTED_STRUCTURE = 6
    INCORRECT_SERVER_CERTIFICATE = 7
    INCORRECT_CLIENT_CERTIFICATE = 8
    INCORRECT_LOGIN = 9
    BAD_ENCRYPTION = 10
    UNKNOWN_ERROR = 11
